name: run MedalHelper

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 12 * * *"

jobs:
    MedalHelper:
        runs-on: ubuntu-latest
        steps:
            - run: docker pull ghcr.io/threecatslovefish/medalhelper:latest
            - run: touch users.yaml
            - run: |
                   echo 'USERS:' >> users.yaml
                   echo '  - access_key: ${{ secrets.BILI_ACCESS }}' >> users.yaml
                   echo '    push_name: fans' >> users.yaml
                   echo '  - access_key: ${{ secrets.BILI_ACCESS2 }}' >> users.yaml
                   echo '    push_name: fans' >> users.yaml
                   echo 'DANMU: ["(⌒▽⌒)."]' >> users.yaml
                   echo 'CD:' >> users.yaml
                   echo '  async: 0' >> users.yaml
                   echo '  retry: 1' >> users.yamlgit config user.email 
                   echo '  max_try: 10' >> users.yaml
                   echo '  like: 2' >> users.yaml
                   echo '  danmu: 6' >> users.yaml
                   echo 'PUSH:' >> users.yaml
                   echo '  - name: "fans"' >> users.yaml
                   echo '    token: "${{ secrets.PUSH_TOKEN }}"' >> users.yaml
                   echo '    type: "push_plus"' >> users.yaml
                   echo '    url: "http://www.pushplus.plus/send"' >> users.yaml
            - run: docker run -i --rm -v $(pwd)/users.yaml:/config/users.yaml ghcr.io/threecatslovefish/medalhelper -start
